{{- if .Values.ingress.enabled -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "xwiki.fullname" . }}
  annotations:
  {{- if .Values.ingress.annotations }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "xwiki.standard-labels" . | nindent 4 }}
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
          service:
            name: {{ template "xwiki.fullname" . }}
            port:
              number: {{ .Values.service.externalPort }}
          {{- else }}
          serviceName: {{ template "xwiki.fullname" . }}
          servicePort: {{ .Values.service.externalPort }}
          {{- end }}
    {{- if .Values.ingress.hostName }}
    host: {{ .Values.ingress.hostName | quote }}
    {{- end -}}
  {{- if .Values.ingress.tls }}
  tls: {{ toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
{{- end -}}
