apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xwiki
  labels:
    {{- include "xwiki.standard-labels" . | nindent 4 }}
spec:
  accessModes:
    - {{.Values.storageAccessMode}}
  resources:
    requests:
      storage: {{ .Values.storage }}
    {{- if .Values.storageClass }}
    storageClassName: {{ .Values.storageClass | quote }}
    {{- end }}
